# Generated by Django 5.1.5 on 2025-02-03 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionPacientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='analisis_ai',
            field=models.TextField(blank=True, null=True),
        ),
    ]
